<h1>Machine Learning - Linear Regression</h1>

In [1]:
!conda install scikit-learn

Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/Python36

  added / updated specs: 
    - scikit-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-19.1.1                 |           py37_0         1.8 MB
    mkl-2019.4                 |              243       204.1 MB
    sqlite-3.28.0              |       h7b6447c_0         1.9 MB
    scikit-learn-0.21.2        |   py37hd81dba3_0         6.7 MB
    joblib-0.13.2              |           py37_0         363 KB
    python-3.7.3               |       h0371630_0        36.7 MB
    certifi-2019.6.16          |           py37_0         154 KB
    numpy-base-1.16.4          |   py37hde5b4d6_0         4.4 MB
    libgcc-ng-9.1.0            |       hdf63c60_0         8.1 MB
    mkl_fft-1.0.12             |   py37ha843d7b_0         172 KB
    mkl-service-2.0.2          |   py37h7b6447c_0          70 

<h2>Import Linear Regression and assign it a variable called model</h2>

In [1]:
from sklearn.linear_model import LinearRegression

In [2]:
model = LinearRegression(normalize=True)

In [3]:
print(model)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)


In [4]:
import numpy as np

<h2>Call in the train_test_split module from sklearn</h2>
<h3>(sklearn.model_selection)<h3>

In [10]:
from sklearn.model_selection import train_test_split

<h3>Create some random data</h3>

X are the features, and y is the label for the feature rows

In [6]:
X,y = np.arange(10).reshape((5,2)),range(5)

In [7]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
list(y)

[0, 1, 2, 3, 4]

<h2>train_test_split</h2>

<li>Set up the train_test_split process for X (features) and y(label)
<li>test_size is 30%    

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [12]:
X_train

array([[4, 5],
       [0, 1],
       [2, 3]])

In [13]:
y_train

[2, 0, 1]

In [14]:
X_test

array([[6, 7],
       [8, 9]])

In [15]:
y_test

[3, 4]

<h2>Fit</h2>
<h4>(the training data)</h4>

<li>With the train_test_split data, now train/Fit the model
<li> Use model.fit() on X_train and y_train (all training data)
<li><b>Supervised Learning</b> accepts two arguments: data/feature X, labels y (example: model.fit(X,y))  
<li><b>Unsupervised Learning</b> accepts one argument: data/feature X (example: model.fit(X))    

In [16]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

<li> Now the model has been fit and trained on the training data
<li>The model is ready to predict labels or values on the test set!

<h2>Predict</h2>
<h4>(The test data)</h4>

<li>Get the predicted values using the predict method on the X_test features
<li>model.predict()
<li>For <b>Supervised Learning</b> predict the label of a new set of data. This method accpets one argument.
<li>(Example: model.predict(X_new)) 
<li>model.predict() is used for clustering algorithms in <b>Unsupervised</b> learning    

In [18]:
predictions = model.predict(X_new)

<h3>Predict_proba</h3>

<li>model.predict_proba()
<li>Used for classification problems
<li>Returns the probability that a new observation is in each categorical label. 
<li>The label with the highest probability is returned via model.predict()    

 <h3>Score</h3>

<li> For <b>Supervised</b> classification and regression problems
<li>Scores are between 0 and 1; the better the fit being closer to 1  
<li> model.score()    

<h2>Transform</h2>

<li>Used in <b>Unsupervised</b> learning
<li>Transform new data into the new basis
<li>This takes only one arguement, and returns the new reprsentation of the data based on the <b>unsupervised</b> model
<li>model.transform(X_new)

<h2>fit_transform</h2>

<li>Used for <b>unsupervised</b> learning
<li>This more efficiently performs fit and a transform on the same input data
<li>model.fit_transform()    

<li>From here, now evaluate the model using a ML algorithm 
<li>(i.e., Regression,Classification, Clustering, etc.)