<h1> NumPy Operations</h1>
<h2> - Array with Array</h2>
<h2> - Array with Scalars</h2>
<h2> - Universal Array Functions<h2>

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h3> Basic Array Operations</h3>

In [5]:
arr + arr      # Adding two arrays together

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr - arr     # Subtracting two arrays

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr * arr     # Multiplying two arrays

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [18]:
arr ** arr    # Exponent with two arrays

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

<h3> Basic Array with Scalar Operations</h3>

In [9]:
arr + 100     # Using a scalar (100) to add to an array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
arr * 100    # Using a scalar (100) to multiply to an array

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [11]:
arr - 100    # Using a scalar (100) to subtract to an array

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [17]:
arr ** 2     # Using a scalar as an exponental value (2), to square the array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
arr / arr    # Gives 'RuntimeWarning:' because 0/0 returns Nan, won't get an error but a warning

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [15]:
1 / arr  # Gives 'RuntimeWarning:' because 1/0 gives infinty (inf)

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

<h3> Universal Array Functions</h3>

In [32]:
np.add(arr,arr)         # ADD()
                        # Adding two arrays

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
np.subtract(arr,arr)    # SUBTRACT ()
                        # Subtracting two arrays

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.multiply(arr,arr)    # MULTIPLY()
                        # Multiplying two arrays

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [37]:
np.divide(arr,arr)      # DIVIDE()
                        # Dividing two arrays

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [19]:
np.sqrt(arr)        # SQRT()
                    # To get the sqaure root of every element in arr

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [20]:
np.exp(arr)         # EXP()
                    # To get the exponential of every element in arr

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [22]:
np.max(arr)         # MAX()
                    # To get the maximum value in arr

10

In [23]:
np.min(arr)         # MIN()
                    # To get the mininmal value in arr

0

In [24]:
np.sin(arr)         # SIN()
                    # To get the sin of every element in arr

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [25]:
np.cos(arr)         # COS()
                    # To get the cosign of every element in arr

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [27]:
np.log(arr)         # LOG()
                    # To get the Logarithmic of every element in arr

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

<h3> Link to more information on Universal Functions for Numpy</h3>

https://docs.scipy.org/doc/numpy/reference/ufuncs.html