<h1>Introduction to NumPy Arrays</h1>

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [6]:
arr = np.array(my_list) # Cast a one dimensional array

In [7]:
arr

array([1, 2, 3])

In [10]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_mat)  # Two dimensional array (2 sets of brackets) 3x3 (3 rows, 3 columns)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<h2>Numpy Arange</h2>

In [14]:
np.arange(0,11,2)   # Numpy arange method similar to python range(), used to generate arrays quickly. 
                    # Give start and stop value (and step count if necessary)
                    # This example starts at 0, stops at 11 and steps by 2 for even values

array([ 0,  2,  4,  6,  8, 10])

In [30]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

<h2>NumPy Zeros and Ones</h2>

In [16]:
np.zeros(3)         # To get all zeros
                    # This examples gives 3 zero values

array([ 0.,  0.,  0.])

In [18]:
np.zeros((5,5))     # A tuple of zeros
                    # This example gives 5x5 zeros from the tuple(5,5)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [20]:
np.zeros((2,3))   # 2x3 array of zeros created by tuple(2,3)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [22]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

<h2>NumPy Linspace</h2>

In [29]:
np.linspace(0,5,100)     # Linspace: provide start, stop, and distance between each value (the specified interval)
                         # Returns evenly spaced over a specified interval
                         # This example returns a 1 dimensional array from 0 to 5, with 100 evenly spaced points between 0 and 5

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

<h2>Identity Matrix using NumPy</h2>

In [5]:
np.eye(4)      # Eye
               # 2 dimensional array, rows and columns are the same size (Takes only one argument)
               # Used to provide zeros and ones
               # Ones are diagonal

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

<h3> Random Numbers</h3>

In [34]:
np.random.rand(5)    # RAND
                     # 1 dimensional array of random numbers, based on the value provided 
                     # Random sample of numbers are uniformly distributed between 0 and 1

array([ 0.82704918,  0.4291216 ,  0.67049251,  0.75782795,  0.61012561])

In [37]:
np.random.rand(10)   # This example provides 10 random numbers between 0 and 1

array([ 0.00781381,  0.18550234,  0.93627762,  0.39582837,  0.75116074,
        0.41685195,  0.06590642,  0.51952122,  0.79842323,  0.77912565])

In [38]:
np.random.rand(5,5)  # Two dimensional array, pass in two values (not as a tuple)

array([[ 0.93669631,  0.54050318,  0.0285361 ,  0.98174844,  0.43881975],
       [ 0.15698142,  0.56642958,  0.77576585,  0.4082741 ,  0.88151122],
       [ 0.40399126,  0.12926492,  0.89250812,  0.35379505,  0.8728606 ],
       [ 0.19529333,  0.09984875,  0.80600053,  0.62529086,  0.2177796 ],
       [ 0.91609614,  0.78869031,  0.66277728,  0.83659764,  0.51012262]])

In [40]:
np.random.randn(2)    # RANDN
                      # Random numbers returned from a normal distribution, around zero 

array([-1.41007222,  0.6867951 ])

In [41]:
np.random.randn(4,4)  # RANDN
                      # Two dimensional array 4x4, with random numbers
                      # Values passed not as tuples; (just comma seperated values)

array([[-0.62833748, -1.19686445, -0.82270899, -2.33947464],
       [ 0.07235767,  0.26281316, -0.08631764, -0.58888288],
       [-0.8399922 , -0.38952511, -0.8059327 ,  0.3593052 ],
       [-0.02910016,  0.8767743 , -0.07315284, -0.12665325]])

In [6]:
np.random.randint(1,100)   # RANDINT
                           # Returns a random interger from a low to a high number passed into the method (between 1 and 100 in this example)

48

In [7]:
np.random.randint(1,100,10)  # Returns 10 random intergers, between 1 and 100, in this example

array([ 3, 55, 22, 84, 96, 45, 16, 49, 64, 54])

<h3>Attributes and Methods of Arrays</h3>

<h4>RESHAPE</h4>

In [8]:
arr = np.arange(25)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
ranarr = np.random.randint(0,50,10)

In [11]:
ranarr

array([25, 36, 45, 17, 46, 33, 24, 36, 24, 44])

In [12]:
arr.reshape(5,5)    # RESHAPE
                    # Return an array of same data, but with a new shape
                    # Notice in arr above, how the array is 1 dimensional
                    # Reshape made the array 2 dimensional, as a 5x5. 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
arr.reshape(5,10)   # An Error will be returned if the array isn't filled up completely with elements
                    # In this example, 50 elements (5,10) would be needed to fill up the array, 
                    # since arr only has 25 elements defined (arr = np.arange(25)) 
                    # The number of rows x columns should equal the actual number of elements.

ValueError: cannot reshape array of size 25 into shape (5,10)

<h4>MAX and MIN</h4>

In [20]:
ranarr

array([25, 36, 45, 17, 46, 33, 24, 36, 24, 44])

In [19]:
ranarr.max()        # MAX 
                    # Find the max value of an array

46

In [22]:
ranarr.min()        # MIN 
                    # Find the max value of an array

17

In [23]:
ranarr

array([25, 36, 45, 17, 46, 33, 24, 36, 24, 44])

In [24]:
ranarr.argmax()     # ARGMAX()
                    # Find the *index location* of the MAX value

4

In [37]:
ranarr.argmin()     # ARGMIN()
                    # Find the *index location* of the MIN value

3

<h4>SHAPE</h4>

In [27]:
arr.shape           # SHAPE
                    # Get the shape of an array
                    # This example shows the arr array as 1 dimensional with 25 elements

(25,)

In [29]:
arr = arr.reshape(5,5)   # Reshape the array as 5x5

In [30]:
arr.shape           # This now shows the arr array as 5x5

(5, 5)

<h4>Find the data type of an array </h4>

In [31]:
arr.dtype           # DTYPE
                    # This will return the data type for the array
                    # In this example, this is a 64 bit interger data type array

dtype('int64')

<h4>Import functions - Shorthand syntax</h4>

In [32]:
# Instead of typing out np.random.randint(1,100,10),
# Import randint from the numpy.random library

In [40]:
from numpy.random import randint 

In [42]:
randint(1,100,10)      

array([ 8, 61, 55, 99, 64, 27, 69, 96, 15, 86])